[tool.poetry]
name = "sample-poetry-prj"
version = "0.1.0"
description = ""
authors = ["Luiz Claudio <luiz.holanda06@gmail.com>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.10"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
